name: flutter_tournament_bracket
description: "Flutter Tournament Bracket is a Flutter widget for displaying tournament brackets in a visually appealing and interactive way. This package is designed to help you create and display tournament brackets with ease."
version: 0.1.0
repository: https://github.com/Farid023/flutter_tournament_bracket
issue_tracker: https://github.com/Farid023/flutter_tournament_bracket/issues


environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



